// -------------------------------------------------------------
// 
// File Name: hdlsrc\NRPolarEncodeHDL\ceilLog2K.v
// Created: 2022-01-15 05:10:41
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: ceilLog2K
// Source Path: NRPolarEncodeHDL/HDL Algorithm/NR Polar Encoder/configure/order/ceilLog2K
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ceilLog2K
          (K,
           nMax,
           n2);


  input   [9:0] K;  // ufix10
  input   [3:0] nMax;  // ufix4
  output  [3:0] n2;  // ufix4


  reg [3:0] n2_1;  // ufix4


  always @(K, nMax) begin
    if (K <= 10'b0000000100) begin
      //anything less than 5 will be set to 5 later
      n2_1 = 4'b0101;
    end
    else if (K <= 10'b0000001000) begin
      n2_1 = 4'b0110;
    end
    else if (K <= 10'b0000010000) begin
      n2_1 = 4'b0111;
    end
    else if (K <= 10'b0000100000) begin
      n2_1 = 4'b1000;
    end
    else if ((K <= 10'b0001000000) || (nMax == 4'b1001)) begin
      n2_1 = 4'b1001;
    end
    else begin
      //anything higher than 10 will be set to 10 later
      n2_1 = 4'b1010;
    end
  end



  assign n2 = n2_1;

endmodule  // ceilLog2K

