// -------------------------------------------------------------
// 
// File Name: hdlsrc\NRPolarEncodeHDL\itlvMap.v
// Created: 2022-01-15 05:10:41
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: itlvMap
// Source Path: NRPolarEncodeHDL/HDL Algorithm/NR Polar Encoder/configure/itlvMap
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module itlvMap
          (indx,
           addr,
           valid);


  output  indx;  // ufix1
  output  addr;  // ufix1
  output  valid;  // ufix1


  wire pass_out1;  // ufix1
  wire pass_out2;  // ufix1
  wire pass_out3;  // ufix1


  pass u_pass (.indx(pass_out1),  // ufix1
               .addr(pass_out2),  // ufix1
               .valid(pass_out3)  // ufix1
               );

  assign indx = pass_out1;

  assign addr = pass_out2;

  assign valid = pass_out3;

endmodule  // itlvMap

