// -------------------------------------------------------------
// 
// File Name: hdlsrc\NRPolarEncodeHDL\MATLAB_Function.v
// Created: 2022-01-15 05:10:42
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MATLAB_Function
// Source Path: NRPolarEncodeHDL/HDL Algorithm/NR Polar Encoder/encode/MATLAB Function
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MATLAB_Function
          (clk,
           reset,
           enb,
           validIn,
           rst,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   validIn;
  input   rst;
  output  validOut;


  reg  validOut_1;
  reg  reg_rst;
  reg  reg_valid;
  reg  reg_rst_next;
  reg  reg_valid_next;


  always @(posedge clk or posedge reset)
    begin : whdledac_c15_MATLAB_Function_process
      if (reset == 1'b1) begin
        reg_rst <= 1'b0;
        reg_valid <= 1'b0;
      end
      else begin
        if (enb) begin
          reg_rst <= reg_rst_next;
          reg_valid <= reg_valid_next;
        end
      end
    end

  always @(reg_rst, reg_valid, rst, validIn) begin
    if (reg_rst) begin
      validOut_1 = 1'b0;
    end
    else begin
      validOut_1 = validIn;
    end
    reg_rst_next = reg_rst;
    if (rst) begin
      reg_rst_next = 1'b1;
    end
    else if (reg_valid && ( ! validIn)) begin
      reg_rst_next = 1'b0;
    end
    reg_valid_next = validIn;
  end



  assign validOut = validOut_1;

endmodule  // MATLAB_Function

