// -------------------------------------------------------------
// 
// File Name: hdlsrc\NRPolarEncodeHDL\pass_block.v
// Created: 2022-01-15 05:10:42
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pass_block
// Source Path: NRPolarEncodeHDL/HDL Algorithm/NR Polar Encoder/frameMap/addrTranslate/pass
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pass_block
          (clk,
           reset,
           enb,
           addrIn,
           addrOut);


  input   clk;
  input   reset;
  input   enb;
  input   [9:0] addrIn;  // ufix10
  output  [9:0] addrOut;  // ufix10


  reg [9:0] Delay_reg [0:1];  // ufix10 [2]
  wire [9:0] Delay_reg_next [0:1];  // ufix10 [2]
  wire [9:0] Delay_out1;  // ufix10


  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_reg[0] <= 10'b0000000000;
        Delay_reg[1] <= 10'b0000000000;
      end
      else begin
        if (enb) begin
          Delay_reg[0] <= Delay_reg_next[0];
          Delay_reg[1] <= Delay_reg_next[1];
        end
      end
    end

  assign Delay_out1 = Delay_reg[1];
  assign Delay_reg_next[0] = addrIn;
  assign Delay_reg_next[1] = Delay_reg[0];



  assign addrOut = Delay_out1;

endmodule  // pass_block

