// -------------------------------------------------------------
// 
// File Name: hdlsrc\NRPolarEncodeHDL\pass.v
// Created: 2022-01-15 05:10:41
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pass
// Source Path: NRPolarEncodeHDL/HDL Algorithm/NR Polar Encoder/configure/itlvMap/pass
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pass
          (indx,
           addr,
           valid);


  output  indx;  // ufix1
  output  addr;  // ufix1
  output  valid;  // ufix1


  wire Zero1_out1;  // ufix1
  wire Zero2_out1;  // ufix1
  wire Zero_out1;  // ufix1


  assign Zero1_out1 = 1'b0;



  assign indx = Zero1_out1;

  assign Zero2_out1 = 1'b0;



  assign addr = Zero2_out1;

  assign Zero_out1 = 1'b0;



  assign valid = Zero_out1;

endmodule  // pass

