// -------------------------------------------------------------
// 
// File Name: hdlsrc\NRPolarEncodeHDL\Sample_Control_Bus_Creator.v
// Created: 2022-01-15 05:10:42
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Sample_Control_Bus_Creator
// Source Path: NRPolarEncodeHDL/HDL Algorithm/NR Polar Encoder/framing/Sample Control Bus Creator
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Sample_Control_Bus_Creator
          (In1,
           In2,
           In3,
           Out1_start,
           Out1_end,
           Out1_valid);


  input   In1;
  input   In2;
  input   In3;
  output  Out1_start;
  output  Out1_end;
  output  Out1_valid;




  assign Out1_start = In1;

  assign Out1_end = In2;

  assign Out1_valid = In3;

endmodule  // Sample_Control_Bus_Creator

