// -------------------------------------------------------------
// 
// File Name: hdlsrc\NRPolarEncodeHDL\Stage_7.v
// Created: 2022-01-15 05:10:42
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Stage_7
// Source Path: NRPolarEncodeHDL/HDL Algorithm/NR Polar Encoder/encode/Stage 7
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Stage_7
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   dataIn;  // ufix1
  input   validIn;
  output  dataOut;  // ufix1
  output  validOut;


  reg  [0:126] Delay15_reg;  // ufix1 [127]
  wire [0:126] Delay15_reg_next;  // ufix1 [127]
  wire Delay15_out1;
  wire Detect_Increase_out1;
  reg  Delay_out1;
  reg [7:0] HDL_Counter7_out1;  // uint8
  wire [15:0] Multiply6_cast;  // ufix16_En14
  wire Multiply6_out1;  // ufix1
  reg  [0:127] Delay14_reg;  // ufix1 [128]
  wire [0:127] Delay14_reg_next;  // ufix1 [128]
  wire Delay14_out1;  // ufix1
  wire XOR7_out1;  // ufix1
  wire Multiport_Switch7_out1;  // ufix1


  always @(posedge clk or posedge reset)
    begin : Delay15_process
      if (reset == 1'b1) begin
        Delay15_reg[0] <= 1'b0;
        Delay15_reg[1] <= 1'b0;
        Delay15_reg[2] <= 1'b0;
        Delay15_reg[3] <= 1'b0;
        Delay15_reg[4] <= 1'b0;
        Delay15_reg[5] <= 1'b0;
        Delay15_reg[6] <= 1'b0;
        Delay15_reg[7] <= 1'b0;
        Delay15_reg[8] <= 1'b0;
        Delay15_reg[9] <= 1'b0;
        Delay15_reg[10] <= 1'b0;
        Delay15_reg[11] <= 1'b0;
        Delay15_reg[12] <= 1'b0;
        Delay15_reg[13] <= 1'b0;
        Delay15_reg[14] <= 1'b0;
        Delay15_reg[15] <= 1'b0;
        Delay15_reg[16] <= 1'b0;
        Delay15_reg[17] <= 1'b0;
        Delay15_reg[18] <= 1'b0;
        Delay15_reg[19] <= 1'b0;
        Delay15_reg[20] <= 1'b0;
        Delay15_reg[21] <= 1'b0;
        Delay15_reg[22] <= 1'b0;
        Delay15_reg[23] <= 1'b0;
        Delay15_reg[24] <= 1'b0;
        Delay15_reg[25] <= 1'b0;
        Delay15_reg[26] <= 1'b0;
        Delay15_reg[27] <= 1'b0;
        Delay15_reg[28] <= 1'b0;
        Delay15_reg[29] <= 1'b0;
        Delay15_reg[30] <= 1'b0;
        Delay15_reg[31] <= 1'b0;
        Delay15_reg[32] <= 1'b0;
        Delay15_reg[33] <= 1'b0;
        Delay15_reg[34] <= 1'b0;
        Delay15_reg[35] <= 1'b0;
        Delay15_reg[36] <= 1'b0;
        Delay15_reg[37] <= 1'b0;
        Delay15_reg[38] <= 1'b0;
        Delay15_reg[39] <= 1'b0;
        Delay15_reg[40] <= 1'b0;
        Delay15_reg[41] <= 1'b0;
        Delay15_reg[42] <= 1'b0;
        Delay15_reg[43] <= 1'b0;
        Delay15_reg[44] <= 1'b0;
        Delay15_reg[45] <= 1'b0;
        Delay15_reg[46] <= 1'b0;
        Delay15_reg[47] <= 1'b0;
        Delay15_reg[48] <= 1'b0;
        Delay15_reg[49] <= 1'b0;
        Delay15_reg[50] <= 1'b0;
        Delay15_reg[51] <= 1'b0;
        Delay15_reg[52] <= 1'b0;
        Delay15_reg[53] <= 1'b0;
        Delay15_reg[54] <= 1'b0;
        Delay15_reg[55] <= 1'b0;
        Delay15_reg[56] <= 1'b0;
        Delay15_reg[57] <= 1'b0;
        Delay15_reg[58] <= 1'b0;
        Delay15_reg[59] <= 1'b0;
        Delay15_reg[60] <= 1'b0;
        Delay15_reg[61] <= 1'b0;
        Delay15_reg[62] <= 1'b0;
        Delay15_reg[63] <= 1'b0;
        Delay15_reg[64] <= 1'b0;
        Delay15_reg[65] <= 1'b0;
        Delay15_reg[66] <= 1'b0;
        Delay15_reg[67] <= 1'b0;
        Delay15_reg[68] <= 1'b0;
        Delay15_reg[69] <= 1'b0;
        Delay15_reg[70] <= 1'b0;
        Delay15_reg[71] <= 1'b0;
        Delay15_reg[72] <= 1'b0;
        Delay15_reg[73] <= 1'b0;
        Delay15_reg[74] <= 1'b0;
        Delay15_reg[75] <= 1'b0;
        Delay15_reg[76] <= 1'b0;
        Delay15_reg[77] <= 1'b0;
        Delay15_reg[78] <= 1'b0;
        Delay15_reg[79] <= 1'b0;
        Delay15_reg[80] <= 1'b0;
        Delay15_reg[81] <= 1'b0;
        Delay15_reg[82] <= 1'b0;
        Delay15_reg[83] <= 1'b0;
        Delay15_reg[84] <= 1'b0;
        Delay15_reg[85] <= 1'b0;
        Delay15_reg[86] <= 1'b0;
        Delay15_reg[87] <= 1'b0;
        Delay15_reg[88] <= 1'b0;
        Delay15_reg[89] <= 1'b0;
        Delay15_reg[90] <= 1'b0;
        Delay15_reg[91] <= 1'b0;
        Delay15_reg[92] <= 1'b0;
        Delay15_reg[93] <= 1'b0;
        Delay15_reg[94] <= 1'b0;
        Delay15_reg[95] <= 1'b0;
        Delay15_reg[96] <= 1'b0;
        Delay15_reg[97] <= 1'b0;
        Delay15_reg[98] <= 1'b0;
        Delay15_reg[99] <= 1'b0;
        Delay15_reg[100] <= 1'b0;
        Delay15_reg[101] <= 1'b0;
        Delay15_reg[102] <= 1'b0;
        Delay15_reg[103] <= 1'b0;
        Delay15_reg[104] <= 1'b0;
        Delay15_reg[105] <= 1'b0;
        Delay15_reg[106] <= 1'b0;
        Delay15_reg[107] <= 1'b0;
        Delay15_reg[108] <= 1'b0;
        Delay15_reg[109] <= 1'b0;
        Delay15_reg[110] <= 1'b0;
        Delay15_reg[111] <= 1'b0;
        Delay15_reg[112] <= 1'b0;
        Delay15_reg[113] <= 1'b0;
        Delay15_reg[114] <= 1'b0;
        Delay15_reg[115] <= 1'b0;
        Delay15_reg[116] <= 1'b0;
        Delay15_reg[117] <= 1'b0;
        Delay15_reg[118] <= 1'b0;
        Delay15_reg[119] <= 1'b0;
        Delay15_reg[120] <= 1'b0;
        Delay15_reg[121] <= 1'b0;
        Delay15_reg[122] <= 1'b0;
        Delay15_reg[123] <= 1'b0;
        Delay15_reg[124] <= 1'b0;
        Delay15_reg[125] <= 1'b0;
        Delay15_reg[126] <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay15_reg[0] <= Delay15_reg_next[0];
          Delay15_reg[1] <= Delay15_reg_next[1];
          Delay15_reg[2] <= Delay15_reg_next[2];
          Delay15_reg[3] <= Delay15_reg_next[3];
          Delay15_reg[4] <= Delay15_reg_next[4];
          Delay15_reg[5] <= Delay15_reg_next[5];
          Delay15_reg[6] <= Delay15_reg_next[6];
          Delay15_reg[7] <= Delay15_reg_next[7];
          Delay15_reg[8] <= Delay15_reg_next[8];
          Delay15_reg[9] <= Delay15_reg_next[9];
          Delay15_reg[10] <= Delay15_reg_next[10];
          Delay15_reg[11] <= Delay15_reg_next[11];
          Delay15_reg[12] <= Delay15_reg_next[12];
          Delay15_reg[13] <= Delay15_reg_next[13];
          Delay15_reg[14] <= Delay15_reg_next[14];
          Delay15_reg[15] <= Delay15_reg_next[15];
          Delay15_reg[16] <= Delay15_reg_next[16];
          Delay15_reg[17] <= Delay15_reg_next[17];
          Delay15_reg[18] <= Delay15_reg_next[18];
          Delay15_reg[19] <= Delay15_reg_next[19];
          Delay15_reg[20] <= Delay15_reg_next[20];
          Delay15_reg[21] <= Delay15_reg_next[21];
          Delay15_reg[22] <= Delay15_reg_next[22];
          Delay15_reg[23] <= Delay15_reg_next[23];
          Delay15_reg[24] <= Delay15_reg_next[24];
          Delay15_reg[25] <= Delay15_reg_next[25];
          Delay15_reg[26] <= Delay15_reg_next[26];
          Delay15_reg[27] <= Delay15_reg_next[27];
          Delay15_reg[28] <= Delay15_reg_next[28];
          Delay15_reg[29] <= Delay15_reg_next[29];
          Delay15_reg[30] <= Delay15_reg_next[30];
          Delay15_reg[31] <= Delay15_reg_next[31];
          Delay15_reg[32] <= Delay15_reg_next[32];
          Delay15_reg[33] <= Delay15_reg_next[33];
          Delay15_reg[34] <= Delay15_reg_next[34];
          Delay15_reg[35] <= Delay15_reg_next[35];
          Delay15_reg[36] <= Delay15_reg_next[36];
          Delay15_reg[37] <= Delay15_reg_next[37];
          Delay15_reg[38] <= Delay15_reg_next[38];
          Delay15_reg[39] <= Delay15_reg_next[39];
          Delay15_reg[40] <= Delay15_reg_next[40];
          Delay15_reg[41] <= Delay15_reg_next[41];
          Delay15_reg[42] <= Delay15_reg_next[42];
          Delay15_reg[43] <= Delay15_reg_next[43];
          Delay15_reg[44] <= Delay15_reg_next[44];
          Delay15_reg[45] <= Delay15_reg_next[45];
          Delay15_reg[46] <= Delay15_reg_next[46];
          Delay15_reg[47] <= Delay15_reg_next[47];
          Delay15_reg[48] <= Delay15_reg_next[48];
          Delay15_reg[49] <= Delay15_reg_next[49];
          Delay15_reg[50] <= Delay15_reg_next[50];
          Delay15_reg[51] <= Delay15_reg_next[51];
          Delay15_reg[52] <= Delay15_reg_next[52];
          Delay15_reg[53] <= Delay15_reg_next[53];
          Delay15_reg[54] <= Delay15_reg_next[54];
          Delay15_reg[55] <= Delay15_reg_next[55];
          Delay15_reg[56] <= Delay15_reg_next[56];
          Delay15_reg[57] <= Delay15_reg_next[57];
          Delay15_reg[58] <= Delay15_reg_next[58];
          Delay15_reg[59] <= Delay15_reg_next[59];
          Delay15_reg[60] <= Delay15_reg_next[60];
          Delay15_reg[61] <= Delay15_reg_next[61];
          Delay15_reg[62] <= Delay15_reg_next[62];
          Delay15_reg[63] <= Delay15_reg_next[63];
          Delay15_reg[64] <= Delay15_reg_next[64];
          Delay15_reg[65] <= Delay15_reg_next[65];
          Delay15_reg[66] <= Delay15_reg_next[66];
          Delay15_reg[67] <= Delay15_reg_next[67];
          Delay15_reg[68] <= Delay15_reg_next[68];
          Delay15_reg[69] <= Delay15_reg_next[69];
          Delay15_reg[70] <= Delay15_reg_next[70];
          Delay15_reg[71] <= Delay15_reg_next[71];
          Delay15_reg[72] <= Delay15_reg_next[72];
          Delay15_reg[73] <= Delay15_reg_next[73];
          Delay15_reg[74] <= Delay15_reg_next[74];
          Delay15_reg[75] <= Delay15_reg_next[75];
          Delay15_reg[76] <= Delay15_reg_next[76];
          Delay15_reg[77] <= Delay15_reg_next[77];
          Delay15_reg[78] <= Delay15_reg_next[78];
          Delay15_reg[79] <= Delay15_reg_next[79];
          Delay15_reg[80] <= Delay15_reg_next[80];
          Delay15_reg[81] <= Delay15_reg_next[81];
          Delay15_reg[82] <= Delay15_reg_next[82];
          Delay15_reg[83] <= Delay15_reg_next[83];
          Delay15_reg[84] <= Delay15_reg_next[84];
          Delay15_reg[85] <= Delay15_reg_next[85];
          Delay15_reg[86] <= Delay15_reg_next[86];
          Delay15_reg[87] <= Delay15_reg_next[87];
          Delay15_reg[88] <= Delay15_reg_next[88];
          Delay15_reg[89] <= Delay15_reg_next[89];
          Delay15_reg[90] <= Delay15_reg_next[90];
          Delay15_reg[91] <= Delay15_reg_next[91];
          Delay15_reg[92] <= Delay15_reg_next[92];
          Delay15_reg[93] <= Delay15_reg_next[93];
          Delay15_reg[94] <= Delay15_reg_next[94];
          Delay15_reg[95] <= Delay15_reg_next[95];
          Delay15_reg[96] <= Delay15_reg_next[96];
          Delay15_reg[97] <= Delay15_reg_next[97];
          Delay15_reg[98] <= Delay15_reg_next[98];
          Delay15_reg[99] <= Delay15_reg_next[99];
          Delay15_reg[100] <= Delay15_reg_next[100];
          Delay15_reg[101] <= Delay15_reg_next[101];
          Delay15_reg[102] <= Delay15_reg_next[102];
          Delay15_reg[103] <= Delay15_reg_next[103];
          Delay15_reg[104] <= Delay15_reg_next[104];
          Delay15_reg[105] <= Delay15_reg_next[105];
          Delay15_reg[106] <= Delay15_reg_next[106];
          Delay15_reg[107] <= Delay15_reg_next[107];
          Delay15_reg[108] <= Delay15_reg_next[108];
          Delay15_reg[109] <= Delay15_reg_next[109];
          Delay15_reg[110] <= Delay15_reg_next[110];
          Delay15_reg[111] <= Delay15_reg_next[111];
          Delay15_reg[112] <= Delay15_reg_next[112];
          Delay15_reg[113] <= Delay15_reg_next[113];
          Delay15_reg[114] <= Delay15_reg_next[114];
          Delay15_reg[115] <= Delay15_reg_next[115];
          Delay15_reg[116] <= Delay15_reg_next[116];
          Delay15_reg[117] <= Delay15_reg_next[117];
          Delay15_reg[118] <= Delay15_reg_next[118];
          Delay15_reg[119] <= Delay15_reg_next[119];
          Delay15_reg[120] <= Delay15_reg_next[120];
          Delay15_reg[121] <= Delay15_reg_next[121];
          Delay15_reg[122] <= Delay15_reg_next[122];
          Delay15_reg[123] <= Delay15_reg_next[123];
          Delay15_reg[124] <= Delay15_reg_next[124];
          Delay15_reg[125] <= Delay15_reg_next[125];
          Delay15_reg[126] <= Delay15_reg_next[126];
        end
      end
    end

  assign Delay15_out1 = Delay15_reg[126];
  assign Delay15_reg_next[0] = validIn;
  assign Delay15_reg_next[1] = Delay15_reg[0];
  assign Delay15_reg_next[2] = Delay15_reg[1];
  assign Delay15_reg_next[3] = Delay15_reg[2];
  assign Delay15_reg_next[4] = Delay15_reg[3];
  assign Delay15_reg_next[5] = Delay15_reg[4];
  assign Delay15_reg_next[6] = Delay15_reg[5];
  assign Delay15_reg_next[7] = Delay15_reg[6];
  assign Delay15_reg_next[8] = Delay15_reg[7];
  assign Delay15_reg_next[9] = Delay15_reg[8];
  assign Delay15_reg_next[10] = Delay15_reg[9];
  assign Delay15_reg_next[11] = Delay15_reg[10];
  assign Delay15_reg_next[12] = Delay15_reg[11];
  assign Delay15_reg_next[13] = Delay15_reg[12];
  assign Delay15_reg_next[14] = Delay15_reg[13];
  assign Delay15_reg_next[15] = Delay15_reg[14];
  assign Delay15_reg_next[16] = Delay15_reg[15];
  assign Delay15_reg_next[17] = Delay15_reg[16];
  assign Delay15_reg_next[18] = Delay15_reg[17];
  assign Delay15_reg_next[19] = Delay15_reg[18];
  assign Delay15_reg_next[20] = Delay15_reg[19];
  assign Delay15_reg_next[21] = Delay15_reg[20];
  assign Delay15_reg_next[22] = Delay15_reg[21];
  assign Delay15_reg_next[23] = Delay15_reg[22];
  assign Delay15_reg_next[24] = Delay15_reg[23];
  assign Delay15_reg_next[25] = Delay15_reg[24];
  assign Delay15_reg_next[26] = Delay15_reg[25];
  assign Delay15_reg_next[27] = Delay15_reg[26];
  assign Delay15_reg_next[28] = Delay15_reg[27];
  assign Delay15_reg_next[29] = Delay15_reg[28];
  assign Delay15_reg_next[30] = Delay15_reg[29];
  assign Delay15_reg_next[31] = Delay15_reg[30];
  assign Delay15_reg_next[32] = Delay15_reg[31];
  assign Delay15_reg_next[33] = Delay15_reg[32];
  assign Delay15_reg_next[34] = Delay15_reg[33];
  assign Delay15_reg_next[35] = Delay15_reg[34];
  assign Delay15_reg_next[36] = Delay15_reg[35];
  assign Delay15_reg_next[37] = Delay15_reg[36];
  assign Delay15_reg_next[38] = Delay15_reg[37];
  assign Delay15_reg_next[39] = Delay15_reg[38];
  assign Delay15_reg_next[40] = Delay15_reg[39];
  assign Delay15_reg_next[41] = Delay15_reg[40];
  assign Delay15_reg_next[42] = Delay15_reg[41];
  assign Delay15_reg_next[43] = Delay15_reg[42];
  assign Delay15_reg_next[44] = Delay15_reg[43];
  assign Delay15_reg_next[45] = Delay15_reg[44];
  assign Delay15_reg_next[46] = Delay15_reg[45];
  assign Delay15_reg_next[47] = Delay15_reg[46];
  assign Delay15_reg_next[48] = Delay15_reg[47];
  assign Delay15_reg_next[49] = Delay15_reg[48];
  assign Delay15_reg_next[50] = Delay15_reg[49];
  assign Delay15_reg_next[51] = Delay15_reg[50];
  assign Delay15_reg_next[52] = Delay15_reg[51];
  assign Delay15_reg_next[53] = Delay15_reg[52];
  assign Delay15_reg_next[54] = Delay15_reg[53];
  assign Delay15_reg_next[55] = Delay15_reg[54];
  assign Delay15_reg_next[56] = Delay15_reg[55];
  assign Delay15_reg_next[57] = Delay15_reg[56];
  assign Delay15_reg_next[58] = Delay15_reg[57];
  assign Delay15_reg_next[59] = Delay15_reg[58];
  assign Delay15_reg_next[60] = Delay15_reg[59];
  assign Delay15_reg_next[61] = Delay15_reg[60];
  assign Delay15_reg_next[62] = Delay15_reg[61];
  assign Delay15_reg_next[63] = Delay15_reg[62];
  assign Delay15_reg_next[64] = Delay15_reg[63];
  assign Delay15_reg_next[65] = Delay15_reg[64];
  assign Delay15_reg_next[66] = Delay15_reg[65];
  assign Delay15_reg_next[67] = Delay15_reg[66];
  assign Delay15_reg_next[68] = Delay15_reg[67];
  assign Delay15_reg_next[69] = Delay15_reg[68];
  assign Delay15_reg_next[70] = Delay15_reg[69];
  assign Delay15_reg_next[71] = Delay15_reg[70];
  assign Delay15_reg_next[72] = Delay15_reg[71];
  assign Delay15_reg_next[73] = Delay15_reg[72];
  assign Delay15_reg_next[74] = Delay15_reg[73];
  assign Delay15_reg_next[75] = Delay15_reg[74];
  assign Delay15_reg_next[76] = Delay15_reg[75];
  assign Delay15_reg_next[77] = Delay15_reg[76];
  assign Delay15_reg_next[78] = Delay15_reg[77];
  assign Delay15_reg_next[79] = Delay15_reg[78];
  assign Delay15_reg_next[80] = Delay15_reg[79];
  assign Delay15_reg_next[81] = Delay15_reg[80];
  assign Delay15_reg_next[82] = Delay15_reg[81];
  assign Delay15_reg_next[83] = Delay15_reg[82];
  assign Delay15_reg_next[84] = Delay15_reg[83];
  assign Delay15_reg_next[85] = Delay15_reg[84];
  assign Delay15_reg_next[86] = Delay15_reg[85];
  assign Delay15_reg_next[87] = Delay15_reg[86];
  assign Delay15_reg_next[88] = Delay15_reg[87];
  assign Delay15_reg_next[89] = Delay15_reg[88];
  assign Delay15_reg_next[90] = Delay15_reg[89];
  assign Delay15_reg_next[91] = Delay15_reg[90];
  assign Delay15_reg_next[92] = Delay15_reg[91];
  assign Delay15_reg_next[93] = Delay15_reg[92];
  assign Delay15_reg_next[94] = Delay15_reg[93];
  assign Delay15_reg_next[95] = Delay15_reg[94];
  assign Delay15_reg_next[96] = Delay15_reg[95];
  assign Delay15_reg_next[97] = Delay15_reg[96];
  assign Delay15_reg_next[98] = Delay15_reg[97];
  assign Delay15_reg_next[99] = Delay15_reg[98];
  assign Delay15_reg_next[100] = Delay15_reg[99];
  assign Delay15_reg_next[101] = Delay15_reg[100];
  assign Delay15_reg_next[102] = Delay15_reg[101];
  assign Delay15_reg_next[103] = Delay15_reg[102];
  assign Delay15_reg_next[104] = Delay15_reg[103];
  assign Delay15_reg_next[105] = Delay15_reg[104];
  assign Delay15_reg_next[106] = Delay15_reg[105];
  assign Delay15_reg_next[107] = Delay15_reg[106];
  assign Delay15_reg_next[108] = Delay15_reg[107];
  assign Delay15_reg_next[109] = Delay15_reg[108];
  assign Delay15_reg_next[110] = Delay15_reg[109];
  assign Delay15_reg_next[111] = Delay15_reg[110];
  assign Delay15_reg_next[112] = Delay15_reg[111];
  assign Delay15_reg_next[113] = Delay15_reg[112];
  assign Delay15_reg_next[114] = Delay15_reg[113];
  assign Delay15_reg_next[115] = Delay15_reg[114];
  assign Delay15_reg_next[116] = Delay15_reg[115];
  assign Delay15_reg_next[117] = Delay15_reg[116];
  assign Delay15_reg_next[118] = Delay15_reg[117];
  assign Delay15_reg_next[119] = Delay15_reg[118];
  assign Delay15_reg_next[120] = Delay15_reg[119];
  assign Delay15_reg_next[121] = Delay15_reg[120];
  assign Delay15_reg_next[122] = Delay15_reg[121];
  assign Delay15_reg_next[123] = Delay15_reg[122];
  assign Delay15_reg_next[124] = Delay15_reg[123];
  assign Delay15_reg_next[125] = Delay15_reg[124];
  assign Delay15_reg_next[126] = Delay15_reg[125];



  Detect_Increase_block6 u_Detect_Increase (.clk(clk),
                                            .reset(reset),
                                            .enb(enb),
                                            .U(Delay15_out1),
                                            .Y(Detect_Increase_out1)
                                            );

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay_out1 <= Delay15_out1;
        end
      end
    end



  // Free running, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  always @(posedge clk or posedge reset)
    begin : HDL_Counter7_process
      if (reset == 1'b1) begin
        HDL_Counter7_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          if (Detect_Increase_out1 == 1'b1) begin
            HDL_Counter7_out1 <= 8'b00000000;
          end
          else if (Delay_out1 == 1'b1) begin
            HDL_Counter7_out1 <= HDL_Counter7_out1 + 8'b00000001;
          end
        end
      end
    end



  assign Multiply6_cast = {1'b0, {HDL_Counter7_out1, 7'b0000000}};
  assign Multiply6_out1 = Multiply6_cast[14];



  always @(posedge clk or posedge reset)
    begin : Delay14_process
      if (reset == 1'b1) begin
        Delay14_reg[0] <= 1'b0;
        Delay14_reg[1] <= 1'b0;
        Delay14_reg[2] <= 1'b0;
        Delay14_reg[3] <= 1'b0;
        Delay14_reg[4] <= 1'b0;
        Delay14_reg[5] <= 1'b0;
        Delay14_reg[6] <= 1'b0;
        Delay14_reg[7] <= 1'b0;
        Delay14_reg[8] <= 1'b0;
        Delay14_reg[9] <= 1'b0;
        Delay14_reg[10] <= 1'b0;
        Delay14_reg[11] <= 1'b0;
        Delay14_reg[12] <= 1'b0;
        Delay14_reg[13] <= 1'b0;
        Delay14_reg[14] <= 1'b0;
        Delay14_reg[15] <= 1'b0;
        Delay14_reg[16] <= 1'b0;
        Delay14_reg[17] <= 1'b0;
        Delay14_reg[18] <= 1'b0;
        Delay14_reg[19] <= 1'b0;
        Delay14_reg[20] <= 1'b0;
        Delay14_reg[21] <= 1'b0;
        Delay14_reg[22] <= 1'b0;
        Delay14_reg[23] <= 1'b0;
        Delay14_reg[24] <= 1'b0;
        Delay14_reg[25] <= 1'b0;
        Delay14_reg[26] <= 1'b0;
        Delay14_reg[27] <= 1'b0;
        Delay14_reg[28] <= 1'b0;
        Delay14_reg[29] <= 1'b0;
        Delay14_reg[30] <= 1'b0;
        Delay14_reg[31] <= 1'b0;
        Delay14_reg[32] <= 1'b0;
        Delay14_reg[33] <= 1'b0;
        Delay14_reg[34] <= 1'b0;
        Delay14_reg[35] <= 1'b0;
        Delay14_reg[36] <= 1'b0;
        Delay14_reg[37] <= 1'b0;
        Delay14_reg[38] <= 1'b0;
        Delay14_reg[39] <= 1'b0;
        Delay14_reg[40] <= 1'b0;
        Delay14_reg[41] <= 1'b0;
        Delay14_reg[42] <= 1'b0;
        Delay14_reg[43] <= 1'b0;
        Delay14_reg[44] <= 1'b0;
        Delay14_reg[45] <= 1'b0;
        Delay14_reg[46] <= 1'b0;
        Delay14_reg[47] <= 1'b0;
        Delay14_reg[48] <= 1'b0;
        Delay14_reg[49] <= 1'b0;
        Delay14_reg[50] <= 1'b0;
        Delay14_reg[51] <= 1'b0;
        Delay14_reg[52] <= 1'b0;
        Delay14_reg[53] <= 1'b0;
        Delay14_reg[54] <= 1'b0;
        Delay14_reg[55] <= 1'b0;
        Delay14_reg[56] <= 1'b0;
        Delay14_reg[57] <= 1'b0;
        Delay14_reg[58] <= 1'b0;
        Delay14_reg[59] <= 1'b0;
        Delay14_reg[60] <= 1'b0;
        Delay14_reg[61] <= 1'b0;
        Delay14_reg[62] <= 1'b0;
        Delay14_reg[63] <= 1'b0;
        Delay14_reg[64] <= 1'b0;
        Delay14_reg[65] <= 1'b0;
        Delay14_reg[66] <= 1'b0;
        Delay14_reg[67] <= 1'b0;
        Delay14_reg[68] <= 1'b0;
        Delay14_reg[69] <= 1'b0;
        Delay14_reg[70] <= 1'b0;
        Delay14_reg[71] <= 1'b0;
        Delay14_reg[72] <= 1'b0;
        Delay14_reg[73] <= 1'b0;
        Delay14_reg[74] <= 1'b0;
        Delay14_reg[75] <= 1'b0;
        Delay14_reg[76] <= 1'b0;
        Delay14_reg[77] <= 1'b0;
        Delay14_reg[78] <= 1'b0;
        Delay14_reg[79] <= 1'b0;
        Delay14_reg[80] <= 1'b0;
        Delay14_reg[81] <= 1'b0;
        Delay14_reg[82] <= 1'b0;
        Delay14_reg[83] <= 1'b0;
        Delay14_reg[84] <= 1'b0;
        Delay14_reg[85] <= 1'b0;
        Delay14_reg[86] <= 1'b0;
        Delay14_reg[87] <= 1'b0;
        Delay14_reg[88] <= 1'b0;
        Delay14_reg[89] <= 1'b0;
        Delay14_reg[90] <= 1'b0;
        Delay14_reg[91] <= 1'b0;
        Delay14_reg[92] <= 1'b0;
        Delay14_reg[93] <= 1'b0;
        Delay14_reg[94] <= 1'b0;
        Delay14_reg[95] <= 1'b0;
        Delay14_reg[96] <= 1'b0;
        Delay14_reg[97] <= 1'b0;
        Delay14_reg[98] <= 1'b0;
        Delay14_reg[99] <= 1'b0;
        Delay14_reg[100] <= 1'b0;
        Delay14_reg[101] <= 1'b0;
        Delay14_reg[102] <= 1'b0;
        Delay14_reg[103] <= 1'b0;
        Delay14_reg[104] <= 1'b0;
        Delay14_reg[105] <= 1'b0;
        Delay14_reg[106] <= 1'b0;
        Delay14_reg[107] <= 1'b0;
        Delay14_reg[108] <= 1'b0;
        Delay14_reg[109] <= 1'b0;
        Delay14_reg[110] <= 1'b0;
        Delay14_reg[111] <= 1'b0;
        Delay14_reg[112] <= 1'b0;
        Delay14_reg[113] <= 1'b0;
        Delay14_reg[114] <= 1'b0;
        Delay14_reg[115] <= 1'b0;
        Delay14_reg[116] <= 1'b0;
        Delay14_reg[117] <= 1'b0;
        Delay14_reg[118] <= 1'b0;
        Delay14_reg[119] <= 1'b0;
        Delay14_reg[120] <= 1'b0;
        Delay14_reg[121] <= 1'b0;
        Delay14_reg[122] <= 1'b0;
        Delay14_reg[123] <= 1'b0;
        Delay14_reg[124] <= 1'b0;
        Delay14_reg[125] <= 1'b0;
        Delay14_reg[126] <= 1'b0;
        Delay14_reg[127] <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay14_reg[0] <= Delay14_reg_next[0];
          Delay14_reg[1] <= Delay14_reg_next[1];
          Delay14_reg[2] <= Delay14_reg_next[2];
          Delay14_reg[3] <= Delay14_reg_next[3];
          Delay14_reg[4] <= Delay14_reg_next[4];
          Delay14_reg[5] <= Delay14_reg_next[5];
          Delay14_reg[6] <= Delay14_reg_next[6];
          Delay14_reg[7] <= Delay14_reg_next[7];
          Delay14_reg[8] <= Delay14_reg_next[8];
          Delay14_reg[9] <= Delay14_reg_next[9];
          Delay14_reg[10] <= Delay14_reg_next[10];
          Delay14_reg[11] <= Delay14_reg_next[11];
          Delay14_reg[12] <= Delay14_reg_next[12];
          Delay14_reg[13] <= Delay14_reg_next[13];
          Delay14_reg[14] <= Delay14_reg_next[14];
          Delay14_reg[15] <= Delay14_reg_next[15];
          Delay14_reg[16] <= Delay14_reg_next[16];
          Delay14_reg[17] <= Delay14_reg_next[17];
          Delay14_reg[18] <= Delay14_reg_next[18];
          Delay14_reg[19] <= Delay14_reg_next[19];
          Delay14_reg[20] <= Delay14_reg_next[20];
          Delay14_reg[21] <= Delay14_reg_next[21];
          Delay14_reg[22] <= Delay14_reg_next[22];
          Delay14_reg[23] <= Delay14_reg_next[23];
          Delay14_reg[24] <= Delay14_reg_next[24];
          Delay14_reg[25] <= Delay14_reg_next[25];
          Delay14_reg[26] <= Delay14_reg_next[26];
          Delay14_reg[27] <= Delay14_reg_next[27];
          Delay14_reg[28] <= Delay14_reg_next[28];
          Delay14_reg[29] <= Delay14_reg_next[29];
          Delay14_reg[30] <= Delay14_reg_next[30];
          Delay14_reg[31] <= Delay14_reg_next[31];
          Delay14_reg[32] <= Delay14_reg_next[32];
          Delay14_reg[33] <= Delay14_reg_next[33];
          Delay14_reg[34] <= Delay14_reg_next[34];
          Delay14_reg[35] <= Delay14_reg_next[35];
          Delay14_reg[36] <= Delay14_reg_next[36];
          Delay14_reg[37] <= Delay14_reg_next[37];
          Delay14_reg[38] <= Delay14_reg_next[38];
          Delay14_reg[39] <= Delay14_reg_next[39];
          Delay14_reg[40] <= Delay14_reg_next[40];
          Delay14_reg[41] <= Delay14_reg_next[41];
          Delay14_reg[42] <= Delay14_reg_next[42];
          Delay14_reg[43] <= Delay14_reg_next[43];
          Delay14_reg[44] <= Delay14_reg_next[44];
          Delay14_reg[45] <= Delay14_reg_next[45];
          Delay14_reg[46] <= Delay14_reg_next[46];
          Delay14_reg[47] <= Delay14_reg_next[47];
          Delay14_reg[48] <= Delay14_reg_next[48];
          Delay14_reg[49] <= Delay14_reg_next[49];
          Delay14_reg[50] <= Delay14_reg_next[50];
          Delay14_reg[51] <= Delay14_reg_next[51];
          Delay14_reg[52] <= Delay14_reg_next[52];
          Delay14_reg[53] <= Delay14_reg_next[53];
          Delay14_reg[54] <= Delay14_reg_next[54];
          Delay14_reg[55] <= Delay14_reg_next[55];
          Delay14_reg[56] <= Delay14_reg_next[56];
          Delay14_reg[57] <= Delay14_reg_next[57];
          Delay14_reg[58] <= Delay14_reg_next[58];
          Delay14_reg[59] <= Delay14_reg_next[59];
          Delay14_reg[60] <= Delay14_reg_next[60];
          Delay14_reg[61] <= Delay14_reg_next[61];
          Delay14_reg[62] <= Delay14_reg_next[62];
          Delay14_reg[63] <= Delay14_reg_next[63];
          Delay14_reg[64] <= Delay14_reg_next[64];
          Delay14_reg[65] <= Delay14_reg_next[65];
          Delay14_reg[66] <= Delay14_reg_next[66];
          Delay14_reg[67] <= Delay14_reg_next[67];
          Delay14_reg[68] <= Delay14_reg_next[68];
          Delay14_reg[69] <= Delay14_reg_next[69];
          Delay14_reg[70] <= Delay14_reg_next[70];
          Delay14_reg[71] <= Delay14_reg_next[71];
          Delay14_reg[72] <= Delay14_reg_next[72];
          Delay14_reg[73] <= Delay14_reg_next[73];
          Delay14_reg[74] <= Delay14_reg_next[74];
          Delay14_reg[75] <= Delay14_reg_next[75];
          Delay14_reg[76] <= Delay14_reg_next[76];
          Delay14_reg[77] <= Delay14_reg_next[77];
          Delay14_reg[78] <= Delay14_reg_next[78];
          Delay14_reg[79] <= Delay14_reg_next[79];
          Delay14_reg[80] <= Delay14_reg_next[80];
          Delay14_reg[81] <= Delay14_reg_next[81];
          Delay14_reg[82] <= Delay14_reg_next[82];
          Delay14_reg[83] <= Delay14_reg_next[83];
          Delay14_reg[84] <= Delay14_reg_next[84];
          Delay14_reg[85] <= Delay14_reg_next[85];
          Delay14_reg[86] <= Delay14_reg_next[86];
          Delay14_reg[87] <= Delay14_reg_next[87];
          Delay14_reg[88] <= Delay14_reg_next[88];
          Delay14_reg[89] <= Delay14_reg_next[89];
          Delay14_reg[90] <= Delay14_reg_next[90];
          Delay14_reg[91] <= Delay14_reg_next[91];
          Delay14_reg[92] <= Delay14_reg_next[92];
          Delay14_reg[93] <= Delay14_reg_next[93];
          Delay14_reg[94] <= Delay14_reg_next[94];
          Delay14_reg[95] <= Delay14_reg_next[95];
          Delay14_reg[96] <= Delay14_reg_next[96];
          Delay14_reg[97] <= Delay14_reg_next[97];
          Delay14_reg[98] <= Delay14_reg_next[98];
          Delay14_reg[99] <= Delay14_reg_next[99];
          Delay14_reg[100] <= Delay14_reg_next[100];
          Delay14_reg[101] <= Delay14_reg_next[101];
          Delay14_reg[102] <= Delay14_reg_next[102];
          Delay14_reg[103] <= Delay14_reg_next[103];
          Delay14_reg[104] <= Delay14_reg_next[104];
          Delay14_reg[105] <= Delay14_reg_next[105];
          Delay14_reg[106] <= Delay14_reg_next[106];
          Delay14_reg[107] <= Delay14_reg_next[107];
          Delay14_reg[108] <= Delay14_reg_next[108];
          Delay14_reg[109] <= Delay14_reg_next[109];
          Delay14_reg[110] <= Delay14_reg_next[110];
          Delay14_reg[111] <= Delay14_reg_next[111];
          Delay14_reg[112] <= Delay14_reg_next[112];
          Delay14_reg[113] <= Delay14_reg_next[113];
          Delay14_reg[114] <= Delay14_reg_next[114];
          Delay14_reg[115] <= Delay14_reg_next[115];
          Delay14_reg[116] <= Delay14_reg_next[116];
          Delay14_reg[117] <= Delay14_reg_next[117];
          Delay14_reg[118] <= Delay14_reg_next[118];
          Delay14_reg[119] <= Delay14_reg_next[119];
          Delay14_reg[120] <= Delay14_reg_next[120];
          Delay14_reg[121] <= Delay14_reg_next[121];
          Delay14_reg[122] <= Delay14_reg_next[122];
          Delay14_reg[123] <= Delay14_reg_next[123];
          Delay14_reg[124] <= Delay14_reg_next[124];
          Delay14_reg[125] <= Delay14_reg_next[125];
          Delay14_reg[126] <= Delay14_reg_next[126];
          Delay14_reg[127] <= Delay14_reg_next[127];
        end
      end
    end

  assign Delay14_out1 = Delay14_reg[127];
  assign Delay14_reg_next[0] = dataIn;
  assign Delay14_reg_next[1] = Delay14_reg[0];
  assign Delay14_reg_next[2] = Delay14_reg[1];
  assign Delay14_reg_next[3] = Delay14_reg[2];
  assign Delay14_reg_next[4] = Delay14_reg[3];
  assign Delay14_reg_next[5] = Delay14_reg[4];
  assign Delay14_reg_next[6] = Delay14_reg[5];
  assign Delay14_reg_next[7] = Delay14_reg[6];
  assign Delay14_reg_next[8] = Delay14_reg[7];
  assign Delay14_reg_next[9] = Delay14_reg[8];
  assign Delay14_reg_next[10] = Delay14_reg[9];
  assign Delay14_reg_next[11] = Delay14_reg[10];
  assign Delay14_reg_next[12] = Delay14_reg[11];
  assign Delay14_reg_next[13] = Delay14_reg[12];
  assign Delay14_reg_next[14] = Delay14_reg[13];
  assign Delay14_reg_next[15] = Delay14_reg[14];
  assign Delay14_reg_next[16] = Delay14_reg[15];
  assign Delay14_reg_next[17] = Delay14_reg[16];
  assign Delay14_reg_next[18] = Delay14_reg[17];
  assign Delay14_reg_next[19] = Delay14_reg[18];
  assign Delay14_reg_next[20] = Delay14_reg[19];
  assign Delay14_reg_next[21] = Delay14_reg[20];
  assign Delay14_reg_next[22] = Delay14_reg[21];
  assign Delay14_reg_next[23] = Delay14_reg[22];
  assign Delay14_reg_next[24] = Delay14_reg[23];
  assign Delay14_reg_next[25] = Delay14_reg[24];
  assign Delay14_reg_next[26] = Delay14_reg[25];
  assign Delay14_reg_next[27] = Delay14_reg[26];
  assign Delay14_reg_next[28] = Delay14_reg[27];
  assign Delay14_reg_next[29] = Delay14_reg[28];
  assign Delay14_reg_next[30] = Delay14_reg[29];
  assign Delay14_reg_next[31] = Delay14_reg[30];
  assign Delay14_reg_next[32] = Delay14_reg[31];
  assign Delay14_reg_next[33] = Delay14_reg[32];
  assign Delay14_reg_next[34] = Delay14_reg[33];
  assign Delay14_reg_next[35] = Delay14_reg[34];
  assign Delay14_reg_next[36] = Delay14_reg[35];
  assign Delay14_reg_next[37] = Delay14_reg[36];
  assign Delay14_reg_next[38] = Delay14_reg[37];
  assign Delay14_reg_next[39] = Delay14_reg[38];
  assign Delay14_reg_next[40] = Delay14_reg[39];
  assign Delay14_reg_next[41] = Delay14_reg[40];
  assign Delay14_reg_next[42] = Delay14_reg[41];
  assign Delay14_reg_next[43] = Delay14_reg[42];
  assign Delay14_reg_next[44] = Delay14_reg[43];
  assign Delay14_reg_next[45] = Delay14_reg[44];
  assign Delay14_reg_next[46] = Delay14_reg[45];
  assign Delay14_reg_next[47] = Delay14_reg[46];
  assign Delay14_reg_next[48] = Delay14_reg[47];
  assign Delay14_reg_next[49] = Delay14_reg[48];
  assign Delay14_reg_next[50] = Delay14_reg[49];
  assign Delay14_reg_next[51] = Delay14_reg[50];
  assign Delay14_reg_next[52] = Delay14_reg[51];
  assign Delay14_reg_next[53] = Delay14_reg[52];
  assign Delay14_reg_next[54] = Delay14_reg[53];
  assign Delay14_reg_next[55] = Delay14_reg[54];
  assign Delay14_reg_next[56] = Delay14_reg[55];
  assign Delay14_reg_next[57] = Delay14_reg[56];
  assign Delay14_reg_next[58] = Delay14_reg[57];
  assign Delay14_reg_next[59] = Delay14_reg[58];
  assign Delay14_reg_next[60] = Delay14_reg[59];
  assign Delay14_reg_next[61] = Delay14_reg[60];
  assign Delay14_reg_next[62] = Delay14_reg[61];
  assign Delay14_reg_next[63] = Delay14_reg[62];
  assign Delay14_reg_next[64] = Delay14_reg[63];
  assign Delay14_reg_next[65] = Delay14_reg[64];
  assign Delay14_reg_next[66] = Delay14_reg[65];
  assign Delay14_reg_next[67] = Delay14_reg[66];
  assign Delay14_reg_next[68] = Delay14_reg[67];
  assign Delay14_reg_next[69] = Delay14_reg[68];
  assign Delay14_reg_next[70] = Delay14_reg[69];
  assign Delay14_reg_next[71] = Delay14_reg[70];
  assign Delay14_reg_next[72] = Delay14_reg[71];
  assign Delay14_reg_next[73] = Delay14_reg[72];
  assign Delay14_reg_next[74] = Delay14_reg[73];
  assign Delay14_reg_next[75] = Delay14_reg[74];
  assign Delay14_reg_next[76] = Delay14_reg[75];
  assign Delay14_reg_next[77] = Delay14_reg[76];
  assign Delay14_reg_next[78] = Delay14_reg[77];
  assign Delay14_reg_next[79] = Delay14_reg[78];
  assign Delay14_reg_next[80] = Delay14_reg[79];
  assign Delay14_reg_next[81] = Delay14_reg[80];
  assign Delay14_reg_next[82] = Delay14_reg[81];
  assign Delay14_reg_next[83] = Delay14_reg[82];
  assign Delay14_reg_next[84] = Delay14_reg[83];
  assign Delay14_reg_next[85] = Delay14_reg[84];
  assign Delay14_reg_next[86] = Delay14_reg[85];
  assign Delay14_reg_next[87] = Delay14_reg[86];
  assign Delay14_reg_next[88] = Delay14_reg[87];
  assign Delay14_reg_next[89] = Delay14_reg[88];
  assign Delay14_reg_next[90] = Delay14_reg[89];
  assign Delay14_reg_next[91] = Delay14_reg[90];
  assign Delay14_reg_next[92] = Delay14_reg[91];
  assign Delay14_reg_next[93] = Delay14_reg[92];
  assign Delay14_reg_next[94] = Delay14_reg[93];
  assign Delay14_reg_next[95] = Delay14_reg[94];
  assign Delay14_reg_next[96] = Delay14_reg[95];
  assign Delay14_reg_next[97] = Delay14_reg[96];
  assign Delay14_reg_next[98] = Delay14_reg[97];
  assign Delay14_reg_next[99] = Delay14_reg[98];
  assign Delay14_reg_next[100] = Delay14_reg[99];
  assign Delay14_reg_next[101] = Delay14_reg[100];
  assign Delay14_reg_next[102] = Delay14_reg[101];
  assign Delay14_reg_next[103] = Delay14_reg[102];
  assign Delay14_reg_next[104] = Delay14_reg[103];
  assign Delay14_reg_next[105] = Delay14_reg[104];
  assign Delay14_reg_next[106] = Delay14_reg[105];
  assign Delay14_reg_next[107] = Delay14_reg[106];
  assign Delay14_reg_next[108] = Delay14_reg[107];
  assign Delay14_reg_next[109] = Delay14_reg[108];
  assign Delay14_reg_next[110] = Delay14_reg[109];
  assign Delay14_reg_next[111] = Delay14_reg[110];
  assign Delay14_reg_next[112] = Delay14_reg[111];
  assign Delay14_reg_next[113] = Delay14_reg[112];
  assign Delay14_reg_next[114] = Delay14_reg[113];
  assign Delay14_reg_next[115] = Delay14_reg[114];
  assign Delay14_reg_next[116] = Delay14_reg[115];
  assign Delay14_reg_next[117] = Delay14_reg[116];
  assign Delay14_reg_next[118] = Delay14_reg[117];
  assign Delay14_reg_next[119] = Delay14_reg[118];
  assign Delay14_reg_next[120] = Delay14_reg[119];
  assign Delay14_reg_next[121] = Delay14_reg[120];
  assign Delay14_reg_next[122] = Delay14_reg[121];
  assign Delay14_reg_next[123] = Delay14_reg[122];
  assign Delay14_reg_next[124] = Delay14_reg[123];
  assign Delay14_reg_next[125] = Delay14_reg[124];
  assign Delay14_reg_next[126] = Delay14_reg[125];
  assign Delay14_reg_next[127] = Delay14_reg[126];



  assign XOR7_out1 = dataIn ^ Delay14_out1;



  assign Multiport_Switch7_out1 = (Multiply6_out1 == 1'b0 ? XOR7_out1 :
              Delay14_out1);



  assign dataOut = Multiport_Switch7_out1;

  assign validOut = Delay_out1;

endmodule  // Stage_7

