// -------------------------------------------------------------
// 
// File Name: hdlsrc\NRPolarEncodeHDL\validateConfig.v
// Created: 2022-01-15 05:10:41
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: validateConfig
// Source Path: NRPolarEncodeHDL/HDL Algorithm/NR Polar Encoder/configure/validateConfig
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module validateConfig
          (clk,
           reset,
           enb,
           K,
           E,
           configValid);


  input   clk;
  input   reset;
  input   enb;
  input   [9:0] K;  // ufix10
  input   [16:0] E;  // ufix17
  output  configValid;


  wire uplinkValid_out1;


  uplinkValid u_uplinkValid (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .K(K),  // ufix10
                             .E(E),  // ufix17
                             .configValid(uplinkValid_out1)
                             );

  assign configValid = uplinkValid_out1;

endmodule  // validateConfig

