vlib work
vlog  SimpleDualPortRAM_singlebit.v
vlog  Configuration.v
vlog  channelLoader.v
vlog  coreController.v
vlog  SimpleDualPortRAM_generic.v
vlog  ramNet.v
vlog  ramNet_block.v
vlog  ramNet_block1.v
vlog  ramNet_block2.v
vlog  ramNet_block3.v
vlog  ramNet_block4.v
vlog  TreeMemory.v
vlog  DecoderCore.v
vlog  Decision.v
vlog  PathMem.v
vlog  outputController.v
vlog  endInNet.v
vlog  CRCGenControl.v
vlog  CRCGenCompute.v
vlog  CRCGenerator.v
vlog  CRCCompNet.v
vlog  CRC_Decoder.v
vlog  endInNet_block.v
vlog  CRCGenControl_block.v
vlog  CRCGenCompute_block.v
vlog  CRCGenerator_block.v
vlog  CRCCompNet_block.v
vlog  CRC_Decoder_block.v
vlog  NR_Polar_Decoder.v
vlog  HDL_Algorithm.v
