// -------------------------------------------------------------
// 
// File Name: hdlsrc\NRPolarDecodeHDL\ramNet.v
// Created: 2022-01-15 05:13:24
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: ramNet
// Source Path: NRPolarDecodeHDL/HDL Algorithm/NR Polar Decoder/TreeMemory/ramNet
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ramNet
          (clk,
           reset,
           enb,
           din,
           wr_addr,
           wr_en,
           rd_addr,
           dout);


  input   clk;
  input   reset;
  input   enb;
  input   din;  // ufix1
  input   wr_addr;  // ufix1
  input   wr_en;
  input   rd_addr;  // ufix1
  output  dout;  // ufix1


  wire addrComp_0;
  wire wr_0;
  reg  ramData_0;  // ufix1
  wire addrComp_1;
  wire wr_1;
  reg  ramData_1;  // ufix1
  wire ramDataSel;  // ufix1
  reg  dout_1;  // ufix1


  assign addrComp_0 = wr_addr == 1'b0;



  assign wr_0 = addrComp_0 & wr_en;



  always @(posedge clk or posedge reset)
    begin : reg_rsvd_process
      if (reset == 1'b1) begin
        ramData_0 <= 1'b0;
      end
      else begin
        if (enb && wr_0) begin
          ramData_0 <= din;
        end
      end
    end



  assign addrComp_1 = wr_addr == 1'b1;



  assign wr_1 = addrComp_1 & wr_en;



  always @(posedge clk or posedge reset)
    begin : reg_rsvd_1_process
      if (reset == 1'b1) begin
        ramData_1 <= 1'b0;
      end
      else begin
        if (enb && wr_1) begin
          ramData_1 <= din;
        end
      end
    end



  assign ramDataSel = (rd_addr == 1'b0 ? ramData_0 :
              ramData_1);



  always @(posedge clk or posedge reset)
    begin : reg_rsvd_2_process
      if (reset == 1'b1) begin
        dout_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          dout_1 <= ramDataSel;
        end
      end
    end



  assign dout = dout_1;

endmodule  // ramNet

